@extends('layouts.admin')
@section('content')
@can('bill_create')
<div style="margin-bottom: 10px;" class="row">
    <div class="col-lg-12">
        <a class="btn btn-success" href="{{ route("admin.purchasebill.add") }}">
            Generate New Bill
        </a>
    </div>
</div>
@endcan
<div class="card">
    <div class="card-header">
        Bill List
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable">
                <thead>
                    <tr>
                        <th width="10">
                            S.No
                        </th>
                        <th>Comapny Name</th>
                        <th>
                            Invocie No.
                        </th>
                        <th>Discount</th>
                        <th>
                            Total Amount
                        </th>
                        <th>
                            Created Date
                        </th>
                        <th>
                            Generated By
                        </th>

                        <th>
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($bills as $key => $bill)
                    <tr data-entry-id="{{ $bill->id }}">
                        <td>
                            {{$key+1}}
                        </td>
                        <td>
                            {{getCompanyName('name',$bill->company_id)}}
                        </td>
                        <td>
                            {{ $bill->invoice_no ?? '' }}
                        </td>
                        <td>
                            <span>&#8377;</span> {{$bill->discount}}
                        </td>
                        <td>
                            <span>&#8377;</span> {{ $bill->grandtotal ?? '' }}
                        </td>
                        <td>
                            {{date('d/m/Y',strtotime($bill->created_date))??''}}
                        </td>
                        <td>
                            {{ getUserName($bill->created_by) ?? '' }}
                        </td>
                        <td>
                            @can('bill_show')
                            <a class="btn btn-xs btn-primary" title="view product list"
                                href="{{ route('admin.purchasebill.show', $bill->id) }}">
                                <i class="fa fa-eye"></i>
                            </a>
                            @endcan
                            <a class="btn btn-xs btn-success"
                                href="{{route('admin.purchasebill.generateBill',[Crypt::encrypt($bill->id)])}}"
                                title="print"><i class="fa fa-print"></i> </a>

                        </td>

                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@section('scripts')
@parent
<script>
$(function() {

    $('.datatable:not(.ajaxTable)').DataTable({});
})
</script>
@endsection
@endsection